package com.hai.ws.api;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-14T10:30:49.886+08:00
 * Generated source version: 3.2.1
 */
@WebServiceClient(name = "IHelloWorldService",
        wsdlLocation = "http://192.168.0.101:8090/helloworld?wsdl",
        targetNamespace = "http://api.ws.hai.com/")
public class IHelloWorldService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://api.ws.hai.com/", "IHelloWorldService");
    public final static QName IHelloWorldPort = new QName("http://api.ws.hai.com/", "IHelloWorldPort");

    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.101:8090/helloworld?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IHelloWorldService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://192.168.0.101:8090/helloworld?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IHelloWorldService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IHelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IHelloWorldService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public IHelloWorldService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IHelloWorldService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IHelloWorldService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns IHelloWorld
     */
    @WebEndpoint(name = "IHelloWorldPort")
    public IHelloWorld getIHelloWorldPort() {
        return super.getPort(IHelloWorldPort, IHelloWorld.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns IHelloWorld
     */
    @WebEndpoint(name = "IHelloWorldPort")
    public IHelloWorld getIHelloWorldPort(WebServiceFeature... features) {
        return super.getPort(IHelloWorldPort, IHelloWorld.class, features);
    }

}
